spring.application.name=Antras_PD_PI24SN_consumer
server.port=8082

# Swagger| link: http://localhost:8082/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
spring.jackson.mapper.sort-properties-alphabetically=false